title: Alight Data Visualization Jekyll Blocks
email: ryan.underwood@alight.com
description: Jekyll experiment to build out Data Styles for blog posts, etc. Who knows if this will work, but YOLO.
global_styles: /assets/styles/global.css
baseurl: ""
url: "" 

collections:
  pages:
    output: 'true'
    permalink: /pages/:year/:title

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
